- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/OracleDAO.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/ForumDAOImpl.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/MessageDAOImpl.java
Merge from master from qa: Sifiso mysql changes
> Merge from master from qa: Sifiso mysql changes 

- sakai-11.4/unisa-changes/changes/providers/component/src/webapp/WEB-INF/components.xml
> Disable JLDAP for login

- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/actions/ForumTopicAction.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/ForumRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/MessageRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/TopicRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/ForumDAOImpl.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/MessageDAOImpl.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/TopicDAOImpl.java
Removed the student system references and read from sakai
> Removed the student system references and read from sakai

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeStandardHead.vm
portal change for azure application monitoring
> portal change for azure application monitoring

- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
Changes to base URLs and button display for CourseAdmin/myAdmin
>  Changes to base URLs and button display for CourseAdmin/myAdmin

- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
> Portal change: Sifiso

- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
Error Corrections:JScript for adding ticket to myAdmin URL
> Error Corrections:JScript for adding ticket to myAdmin URL

- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/bundle/sitenav.properties
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
> merge from master to QA 

- sakai-11.4/unisa-changes/changes/master/pom.xml
- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/bundle/sitenav.properties
- sakai-11.4/unisa-tools/unisa-welcome/src/webapp/WEB-INF/web.xml
add application insight for Azure application monitoring
>  add application insight for Azure application monitoring

- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
Modified to hide the option to schedule future announcements
> Modified to hide the option to schedule future announcements

- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/actions/ForumTopicAction.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/ForumRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/MessageRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/OracleDAO.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/TopicRowMapper.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/ForumDAOImpl.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/MessageDAOImpl.java
- sakai-11.4/unisa-tools/unisa-discussionforums/src/java/za/ac/unisa/lms/tools/discussionforums/dao/impl/TopicDAOImpl.java
- sakai-11.4/unisa-tools/unisa-faqs/src/java/za/ac/unisa/lms/tools/faqs/dao/FaqDAO.java
- sakai-11.4/unisa-tools/unisa-welcome/src/java/za/ac/unisa/lms/tools/welcome/dao/WelcomeDisplayQueryDAO.java
> unisa_tools_mqsql_conversions

- sakai-11.4/unisa-tools/unisa-axis/src/webapp/GradebookSyncStudentSystemWebserviceAzure.jws
- sakai-11.4/unisa-tools/unisa-cronjobs/src/java/za/ac/unisa/lms/tools/cronjobs/jobs/GradebookIntegrationJob.java
Workaround gradebooksync without dataLink
> Workaround gradebooksync without dataLink

- sakai-11.4/unisa-tools/unisa-axis/src/webapp/GradebookSyncStudentSystemWebserviceAzure.jws
- sakai-11.4/unisa-tools/unisa-cronjobs/src/java/za/ac/unisa/lms/tools/cronjobs/jobs/GradebookIntegrationJob.java
- sakai-11.4/unisa-tools/unisa-studymaterial/tool/pom.xml
Sonette - Gradebook sync workaround without dataLink
> Sonette - Gradebook sync workaround without dataLink

- sakai-11.4/unisa-tools/unisa-axis/pom.xml
add tools.jar as dependency in pom.xml
> add tools.jar as dependency in pom.xml

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
- sakai-11.4/unisa-tools/unisa-axis/pom.xml
Change Javascript for CAS Ticket
> Change Javascript for CAS Ticket

- sakai-11.4/melete/components/src/webapp/WEB-INF/components.xml
- sakai-11.4/melete/melete-api/src/java/org/etudes/api/app/melete/SectionService.java
- sakai-11.4/melete/melete-app/src/java/org/etudes/tool/melete/EditSectionPage.java
- sakai-11.4/melete/melete-app/src/java/org/etudes/tool/melete/Util.java
- sakai-11.4/melete/melete-app/src/java/org/etudes/tool/melete/ViewSectionsPage.java
- sakai-11.4/melete/melete-hbm/src/java/org/etudes/component/app/melete/ContentResource.hbm.xml
- sakai-11.4/melete/melete-hbm/src/java/org/etudes/component/app/melete/ContentResource.java
- sakai-11.4/melete/melete-impl/src/java/org/etudes/component/app/melete/SectionDB.java
- sakai-11.4/melete/melete-impl/src/java/org/etudes/component/app/melete/SectionServiceImpl.java
melete_changes_from11.4_myUnisa
> melete_changes_from11.4_myUnisa

- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
This is to rollback announcement changes to hide the option to schedule
> This is to rollback announcement changes to hide the option to schedule

- sakai-11.4/unisa-changes/changes/providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProvider.java
> provider changes

- sakai-11.4/unisa-changes/changes/providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProvider.java
> Add myAdmin provider Id

- sakai-11.4/unisa-tools/unisa-axis/axis/pom.xml
- sakai-11.4/unisa-tools/unisa-axis/axis/src/webapp/GradebookSyncStudentSystemWebService.jws
> unisa-axis without dataLink

- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/all_user_posts.hbs
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/authors.hbs
clog: Remove add as connection onpages
> clog: Remove add as connection onpages

- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookSyncBean.java
- sakai-11.4/unisa-tools/unisa-cronjobs/src/java/za/ac/unisa/lms/tools/cronjobs/jobs/GradebookIntegrationJob.java
Signed-off-by: sonette Yzelle <syzelle@unisa.ac.za>
> change unisa-axis to sakai-axis

- sakai-11.4/unisa-changes/changes/lessonbuilder/tool/src/webapp/css/Simplepagetool.css
- sakai-11.4/unisa-tools/unisa-axis/axis/src/webapp/GradebookSyncStudentSystemWebService.jws
Merge Lesson Tool changes in myModulesQA
> Merge Lesson Tool changes in myModulesQA

- sakai-11.4/unisa-changes/overlays/assignment/assignment-tool/tool/src/webapp/tools/sakai.assignment.grades.xml
- sakai-11.4/unisa-changes/overlays/qna/tool/src/bundle/messages.properties
changes to assignment and qna tool
> CR3321_Template2020toolNameChangesUnisa_Changes

- sakai-11.4/qna/tool/src/bundle/messages.properties
- sakai-11.4/unisa-changes/overlays/assignment/assignment-tool/tool/src/webapp/tools/sakai.assignment.grades.xml
- sakai-11.4/unisa-changes/overlays/qna/tool/src/bundle/messages.properties
Changes to assignments and QNA tool
> CR3321_Template2020toolNameUnisa_Changes

- sakai-11.4/unisa-changes/changes/master/pom.xml
Add dependency for template and welcome in master pom
> Add dependency for template and welcome in master pom

- sakai-11.4/unisa-changes/changes/master/pom.xml
- sakai-11.4/welcome/welcome-impl/impl/src/java/org/sakaiproject/welcome/impl/DbWelcomeService.java
> welcome tool oracle to mySql

- sakai-11.4/welcome/welcome-tool/tool/src/java/org/sakaiproject/welcome/tool/WelcomeAction.java
- sakai-11.4/welcome/welcome-tool/tool/src/webapp/vm/welcome/chef_welcome_edit.vm
> welcome text area fix

- sakai-11.4/faqs/faqs-api/api/src/java/org/sakaiproject/faqs/api/FaqsService.java
- sakai-11.4/faqs/faqs-api/api/src/java/org/sakaiproject/faqs/cover/FaqsService.java
- sakai-11.4/faqs/faqs-impl/impl/src/java/org/sakaiproject/faqs/impl/BaseFaqsService.java
- sakai-11.4/faqs/faqs-impl/impl/src/java/org/sakaiproject/faqs/impl/DbFaqsService.java
- sakai-11.4/faqs/faqs-tool/tool/src/java/org/sakaiproject/faqs/tool/FaqsToolAction.java
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_add_category.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_edit_category.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_main_view.vm
> FAd update faq edited

- sakai-11.4/faqs/faqs-api/api/src/java/org/sakaiproject/faqs/api/FaqsService.java
- sakai-11.4/faqs/faqs-api/api/src/java/org/sakaiproject/faqs/cover/FaqsService.java
- sakai-11.4/faqs/faqs-impl/impl/src/java/org/sakaiproject/faqs/impl/BaseFaqsService.java
- sakai-11.4/faqs/faqs-impl/impl/src/java/org/sakaiproject/faqs/impl/DbFaqsService.java
- sakai-11.4/faqs/faqs-tool/tool/src/java/org/sakaiproject/faqs/tool/FaqsToolAction.java
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_add_category.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_add_faq.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_edit_category.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_edit_faq.vm
- sakai-11.4/faqs/faqs-tool/tool/src/webapp/vm/faqs/faqs_main_view.vm
> Faqs save specific

- sakai-11.4/unisa-changes/changes/signup/tool/src/bundle/signupConfig.properties
- sakai-11.4/unisa-changes/changes/signup/tool/src/webapp/WEB-INF/tools/sakai.signup.xml
> unisa-changes for signup

- sakai-11.4/unisa-changes/changes/config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
- sakai-11.4/unisa-changes/changes/login/login-render-engine-impl/pack/src/webapp/vm/defaultskin/xlogin.vm
- sakai-11.4/unisa-changes/changes/web/web-portlet/src/webapp/WEB-INF/sakai/PortletIFrame.xml
- sakai-11.4/unisa-changes/changes/webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
12.6 unisa changes for config, login,web,webservice
> 12.6 unisa changes for config, login,web,webservice

- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- sakai-11.4/unisa-changes/changes/portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/login.vm
- sakai-11.4/unisa-changes/changes/webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
> 12.6_portal fix

- sakai-11.4/unisa-changes/changes/gradebook/app/business/pom.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/GradebookManager.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookManagerHibernateImpl.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookScoringAgentManagerImpl.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookSyncStudentSystemWebServiceService.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookSyncStudentSystemWebServiceServiceLocator.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookSyncStudentSystemWebServiceSoapBindingStub.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookSyncStudentSystemWebService_PortType.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/UnisaGradeBookDAO.java
- sakai-11.4/unisa-changes/changes/gradebook/app/sakai-tool/src/webapp/WEB-INF/tools/sakai.gradebook.tool.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/pom.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/bundle/org/sakaiproject/tool/gradebook/bundle/Messages.properties
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentDetailsBean.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookDependentBean.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookSyncBean.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/OverviewBean.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/pom.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/faces-beans.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/faces-navigation.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/spring-beans.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/assignmentDetails.jsp
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/gradebookSync.jsp
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/inc/breadcrumb.jspf
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/inc/breadcrumbInstructor.jspf
gradebook changes: sync to student system
> gradebook changes: sync to student system

- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/tools/sakai.announcements.xml
- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/tools/sakai.synoptic.announcement.xml
- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-customize.vm
- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-metadata.vm
- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
- sakai-11.4/unisa-changes/changes/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
> 12.6 announcement changes

- sakai-11.4/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentBean.java
- sakai-11.4/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookSetupBean.java
- sakai-11.4/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/SpreadsheetUploadBean.java
- sakai-11.4/gradebook/app/ui/src/webapp/gradebookSetup.jsp
- sakai-11.4/gradebook/app/ui/src/webapp/spreadsheetImport.jsp
Reinstate default sakai Gradebook
> Reinstate default sakai Gradebook

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageWithNav.vm
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
portal skin changes from Martin
> portal skin changes from Martin

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageWithNav.vm
- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
> poral skin changes 3

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/header-snippet.vm
> portal changes 4

- sakai-11.4/unisa-changes/changes/portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm
> portal change

- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/modules/tool/sitemanage/_sitemanage.scss
library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
> Replaced unisa library changes _sitemanage.scss  with

- sakai-11.4/unisa-tools/unisa-cronjobs/src/java/za/ac/unisa/lms/tools/cronjobs/jobs/ONLImportJob.java
Added samigo to import from master to site
> Added samigo to import from master to site

- sakai-11.4/clog/api/src/java/org/sakaiproject/clog/api/ClogMember.java
- sakai-11.4/clog/impl/src/java/org/sakaiproject/clog/impl/SakaiProxyImpl.java
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/all_user_posts.hbs
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/authors.hbs
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/authors_wrapper.hbs
Clog tools Icons changes + Showing initials + surname
> Clog tools Icons changes + Showing initials + surname

- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/authors_wrapper.hbs
- sakai-11.4/clog/tool/src/webapp/js/clog_utils.js
Added pagination and empty title validation.
> Added pagination and empty title validation.

- sakai-11.4/unisa-changes/changes/master/pom.xml
Added the discussion forums dependencies
> Added the discussion forums dependencies

- sakai-11.4/unisa-changes/changes/gradebook/app/business/pom.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/GradebookManager.java
- sakai-11.4/unisa-changes/changes/gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookManagerHibernateImpl.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentDetailsBean.java
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/faces-beans.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/faces-navigation.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/WEB-INF/spring-beans.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/assignmentDetails.jsp
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/webapp/inc/breadcrumbInstructor.jspf
> unisa_changes_gradebook

- sakai-11.4/clog/tool/src/java/org/sakaiproject/clog/tool/entityprovider/ClogAuthorEntityProvider.java
- sakai-11.4/clog/tool/src/webapp/css/clog.css
- sakai-11.4/clog/tool/src/webapp/js/clog_utils.js
> Fix pagination.

- sakai-11.4/clog/tool/src/webapp/css/clog.css
> Fixing Clog CSS problem

- sakai-11.4/clog/impl/src/java/org/sakaiproject/clog/impl/PersistenceManager.java
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/all_user_posts.hbs
- sakai-11.4/clog/tool/src/webapp/WEB-INF/templates/post.hbs
- sakai-11.4/clog/tool/src/webapp/css/clog.css
- sakai-11.4/clog/tool/src/webapp/js/clog_utils.js
- sakai-11.4/unisa-axis/axis/pom.xml
- sakai-11.4/unisa-changes/changes/gradebook/app/ui/src/bundle/org/sakaiproject/tool/gradebook/bundle/Messages.properties
Clog: Correct comments not showing
> Clog: Correct comments not showing

- sakai-11.4/mymodulesmonitor/.tern-project
- sakai-11.4/mymodulesmonitor/pom.xml
- sakai-11.4/mymodulesmonitor/src/main/java/org/sakaiproject/monitor/controller/MonitorController.java
- sakai-11.4/mymodulesmonitor/src/main/webapp/WEB-INF/monitor-servlet.xml
- sakai-11.4/mymodulesmonitor/src/main/webapp/WEB-INF/views/plain.jsp
- sakai-11.4/mymodulesmonitor/src/main/webapp/WEB-INF/views/sakaiDBFail.jsp
- sakai-11.4/mymodulesmonitor/src/main/webapp/WEB-INF/views/testSakaiDB.jsp
- sakai-11.4/mymodulesmonitor/src/main/webapp/WEB-INF/web.xml
- sakai-11.4/mymodulesmonitor/src/main/webapp/index.jsp
> unisa monitor spring tool

- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/base/_bootstrap-defaults.scss
- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/base/_defaults.scss
- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/base/_extendables.scss
- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/base/_icons.scss
- sakai-11.4/unisa-changes/changes/library/src/unisa-master/sass/base/_responsive.scss
unisa changes replace files from 11.4 to unisa master sass base folder
> unisa changes replace files from 11.4 to unisa master sass base folder

- sakai-11.4/unisa-calendar/pom.xml
- sakai-11.4/unisa-calendar/unisa-calendar-impl/impl/pom.xml
> calendar changes for Vijay.

- sakai-11.4/clog/tool/src/webapp/js/clog_utils.js
> clog Validations

- sakai-11.4/unisa-changes/overlays/assignment/assignment-tool/tool/src/webapp/tools/sakai.assignment.grades.xml
Change assessment name to eAssessment
> Change assessment name to eAssessment
